version: "3.8"

services:
  app:
    image: php:8.4-fpm
    container_name: laravel-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./backend/:/var/www
      - ./backend/entrypoint.sh:/entrypoint.sh
    networks:
      - laravel-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    depends_on:
      - db
    ports:
      - "8000:80"
    entrypoint: ["bash", "/entrypoint.sh"]
  
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-network
      - vue-network 

  vue-quasar-app:
    image: node:22.0.0
    container_name: vue-quasar-app
    restart: always
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "9000:9000"
    command: bash -c "yarn install && yarn dev"
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
  laravel-network:
    driver: bridge

volumes:
  pg_data:
    driver: local
