version: "3.8"

services:
  app:
    image: php:8.4-fpm
    container_name: laravel-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - laravel-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    depends_on:
      - db
    ports:
      - "8000:80"
    entrypoint: ["bash", "/entrypoint.sh"]

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-network
    ports:
      - "5432:5432"

networks:
  laravel-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
